services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  server:
    build:
      context: ./server
    command: nodemon server.js
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app

volumes:
  node_modules: {}
