services:
  client:
    build:
      context: ./client
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app

  server:
    build:
      context: ./server
    command: nodemon server.js
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
